version: "3"
services:
  database:
    container_name: learnhub_database
    restart: always
    image: postgres:13-alpine # use latest official postgres version
    environment:
      POSTGRES_USER: ${DB_USERNAME} # configure postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - learnhub-db:/var/lib/postgresql/data/ # persist data even if container shuts down
    env_file:
      - ./.env.prod
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
    networks:
      - application-network

  laravel:
    container_name: learnhub_laravel
    build:
      # context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.3/app
    env_file:
      - ./.env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - "learnhub-service:/var/www/html"
    networks:
      - application-network
    depends_on:
      - database

volumes:
  learnhub-service:
    driver: local
  learnhub-db: # named volumes can be managed easier using docker-compose
    driver: local

networks:
  application-network:
    driver: bridge
