version: "3"
services:
  database:
    container_name: learnhub_database
    restart: always
    image: postgres:13-alpine # Use a stable version of PostgreSQL
    environment:
      POSTGRES_USER: "${DB_USERNAME}" # Configure PostgreSQL
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - learnhub-db:/var/lib/postgresql/data/ # Persist data even if the container shuts down
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432" # Expose the database port, ensuring it matches the one in .env.prod
    networks:
      - application-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  laravel:
    container_name: learnhub_laravel
    build:
      context: . # Specify the build context as the current directory
      dockerfile: Dockerfile # The Dockerfile used to build the image
      args:
        WWWGROUP: "${WWWGROUP}"
    image: learnhub_laravel:latest # Name the image to avoid the build context issue
    env_file:
      - ./.env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80" # Use environment variable for app port, default to 80
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}" # Use environment variable for Vite port, default to 5173
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - "learnhub-service:/var/www/html"
    networks:
      - application-network
    depends_on:
      database:
        condition: service_healthy

volumes:
  learnhub-service:
    driver: local
  learnhub-db:
    driver: local

networks:
  application-network:
    driver: bridge
