version: "3"
services:
    database:
        container_name: learnhub-database
        restart: always
        image: postgres:13-alpine # use latest official postgres version
        environment:
            POSTGRES_USER: ${DB_USERNAME} # configure postgres
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - learnhub-db:/var/lib/postgresql/data/ # persist data even if container shuts down
        env_file:
            - ./.env
        expose:
            - ${DB_PORT}
        ports:
            - ${DB_PORT}:${DB_PORT}
        command: -p ${DB_PORT}
        networks:
            - application-network

volumes:
    learnhub-db: # named volumes can be managed easier using docker-compose
        driver: local

networks:
    application-network:
        driver: bridge
