version: "3.8"

services:
  database:
    container_name: learnhub_database
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - learnhub-db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - application-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  laravel:
    container_name: learnhub_laravel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: learnhub_laravel:latest
    env_file:
      - ./.env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - "learnhub-service:/var/www/html"
      - "./.env.prod:/var/www/html/.env"
    networks:
      - application-network
    depends_on:
      database:
        condition: service_healthy

volumes:
  learnhub-service:
    driver: local
  learnhub-db:
    driver: local

networks:
  application-network:
    driver: bridge
